---

# The "gateway" machine has two interfaces, one on the home network and one on the new libvirt network.
# There is no DHCP yet so the second interface is assigned an IP address.
# Use a kickstart file to set up this networking.

- name: build new server storage volume
  hosts: gateway
  become: yes
  gather_facts: no
  serial: 1
  roles: 
  - role: nick.platform.libvirt_volume
    delegate_to: "{{ groups['hypervisor'][0] }}"
