---

- name: build new server machine
  hosts: dns
  become: yes
  gather_facts: no
  serial: 1
  roles: 
  - role: nick.platform.libvirt_storage
    delegate_to: "{{ groups['hypervisor'][0] }}"
  - role: nick.platform.libvirt_machine_image
    delegate_to: "{{ groups['hypervisor'][0] }}"
  - role: nick.platform.hosts_record
    vars:
      ip_address: "{{ nics[0]['ip'] }}"
    delegate_to: "{{ groups['install_host'][0] }}"

  tasks:

  - name: Wait for new server to be ready
    ansible.builtin.wait_for_connection:
      timeout: 30
    become: no


- name: configure new server machine
  hosts: dns
  become: yes
  gather_facts: no
  serial: 1
  vars_files:
  - vault-credentials.yml
  environment:
    http_proxy: http://gateway.lab.example.com:3128
    HTTPS_PROXY: http://gateway.lab.example.com:3128
    no_proxy: localhost,127.0.0.1,example.com
  roles:
  - nick.platform.managed_node
  - nick.platform.server_cert
  - nick.platform.dns_server
  - nick.platform.cdn_repo_consumer
  - nick.platform.latest_packages


# !!! smoke tests?
# host name1 localhost
# systemctl status chronyd
# ping -c1 localhost
# ping -c1 $(hostname -s)
# ping -c1 $(hostname -f)
# dig +short name1.lab.example.com. @name1.lab.example.com
# answer is 1.2.3.4
# dig -x 1.2.3.4

