---

# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html-single/installing_identity_management/index

# !!! routing may be an issue. 
# subnet has no NAT or home lab IP. 
# all must be run on hypervisor
# or a machine where routing is set up to find this obscure subnet.

- name: build new server machine
  hosts: auth
  become: yes
  gather_facts: no
  serial: 1
  roles: 
  - role: nick.platform.libvirt_storage
    delegate_to: "{{ groups['hypervisor'][0] }}"
  - role: nick.platform.libvirt_machine
    delegate_to: "{{ groups['hypervisor'][0] }}"
  - role: nick.platform.hosts_record
    vars:
      ip_address: "{{ nics[0]['ip'] }}"
    delegate_to: "{{ groups['install_host'][0] }}"

  tasks:

  - name: Wait for new server to be ready
    ansible.builtin.wait_for_connection:
      timeout: 30
    become: no

# !!! idm installer objects to the current DNS server. 
# disable DHCP?
# experimenting with
#  nmcli con modify enp1s0 ipv4.addresses 192.168.134.10/24
#  nmcli con modify enp1s0 ipv4.method manual
#  nmcli con modify enp1s0 ipv4.gateway 192.168.134.1



- name: configure new server machine
  hosts: auth
  become: yes
  gather_facts: yes
  serial: 1
  environment:
    http_proxy: http://gateway.lab.example.com:3128
    HTTPS_PROXY: http://gateway.lab.example.com:3128
    no_proxy: localhost,127.0.0.1,example.com
  roles:
  - nick.platform.managed_node
  - nick.platform.server_cert
  - nick.platform.local_repo_consumer
  - nick.platform.latest_packages
  - nick.integration.ipa_server

  tasks: 

# test 
#
