---

# The "gateway" machine has two interfaces, one on the home network and one on the new libvirt network.
# There is no DHCP yet so the second interface is assigned an IP address.
# Use a kickstart file to set up this networking.

- name: build new server machine
  hosts: gateway
  become: yes
  gather_facts: no
  serial: 1
  roles: 
  - name: build new server storage volume
    role: nick.platform.libvirt_volume
    delegate_to: "{{ groups['hypervisor'][0] }}"
  - name: build new VM
    role: nick.platform.libvirt_machine
    delegate_to: "{{ groups['hypervisor'][0] }}"
  - role: nick.platform.hosts_record
    vars:
      ip_address: "{{ nics[0]['ip'] }}"
    delegate_to: "{{ groups['install_host'][0] }}"

  tasks:

  - name: Wait for new server to be ready
    ansible.builtin.wait_for_connection:
      timeout: 120
    become: no


- name: configure new server machine
  hosts: gateway
  become: yes
  gather_facts: no
  vars_files:
  - vault-rhsm.yml
  serial: 1
  roles:
  - nick.platform.managed_node
  - nick.platform.cdn_repo_consumer
  - nick.platform.latest_packages
  - nick.platform.server_cert
  - nick.platform.squid_proxy
  - nick.platform.dns_forwarder

    # !!! add time_server 
    # https://hardiman.consulting/rhel/9/time/chrony.html
    
# smoke tests 
# !!! add tests
# squid
#   curl -O -L "https://www.redhat.com/index.html" -x "gateway.lab.example.com:3128"
# dns
#   dig @192.168.134.5 dns.lab.example.com
#   dig @192.168.134.5 192.168.134.5
#   dig @192.168.134.5 www.google.com
#   dig @192.168.134.5 142.250.179.22

