---

- name: start a new instance of the machine.
  hosts: ipsal
  become: yes
  gather_facts: no
  serial: 1
  roles: 
  - name: "create a new instance"
    role: nick.platform.libvirt_machine_instance
    delegate_to: "{{ groups['hypervisor'][0] }}"

  tasks:

  - name: Wait for new server to be ready
    ansible.builtin.wait_for_connection:
      timeout: 120
    become: no
