---
- name: build new hypervisor
  hosts: hypervisor
  become: yes
  gather_facts: yes
  roles: 
  - role: nick.platform.libvirt_host
  - role: nick.platform.libvirt_storage
  - role: nick.platform.libvirt_net

