---

# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/managing_networking_infrastructure_services/providing-dhcp-services_networking-infrastructure-services#doc-wrapper

# !!! routing may be an issue. 
# subnet has no NAT or home lab IP. 
# all must be run on hypervisor
# or a machine where routing is set up to find this obscure subnet.

- name: build new server machine
  hosts: dhcp
  become: yes
  gather_facts: no
  serial: 1
  roles: 
  - role: nick.platform.libvirt_storage
    vars:
      kickstart_template: dhcp.ks.j2
    delegate_to: "{{ groups['hypervisor'][0] }}"
  - role: nick.platform.libvirt_machine
    delegate_to: "{{ groups['hypervisor'][0] }}"
  - role: nick.platform.hosts_record
    vars:
      ip_address: "{{ nics[0]['ip'] }}"
    delegate_to: "{{ groups['install_host'][0] }}"

  tasks:

  - name: Wait for new server to be ready
    ansible.builtin.wait_for_connection:
      timeout: 30
    become: no


- name: configure new server machine
  hosts: dhcp
  become: yes
  gather_facts: no
  serial: 1
  vars_files:
  - vault-rhsm.yml
  environment:
    http_proxy: http://gateway.lab.example.com:3128
    HTTPS_PROXY: http://gateway.lab.example.com:3128
    no_proxy: localhost,127.0.0.1,example.com
  roles:
  - nick.platform.managed_node
  - role: nick.platform.hosts_record
    # !!! hardcoded
    vars:
      ip_address: "{{ lab_net_prefix }}.3"
      fqdn: gateway.lab.example.com
      host: gateway
  - nick.platform.cdn_repo_consumer
  - nick.platform.latest_packages
  - nick.platform.server_cert
  - nick.platform.dhcp_server

