
- name: build new server machine
  hosts: hypervisor
  become: yes
  gather_facts: yes
  tasks: 

  # stop a network
  - community.libvirt.virt_net:
      command: destroy
      name: "{{ libvirt_net_name }}"
    ignore_errors: yes

  # delete a network
  - community.libvirt.virt_net:
      state: absent
      name: "{{ libvirt_net_name }}"

  # !!! doesn't work
  # try 
  #   nmcli con delete {{ bridge_nmcli_name }}
  # instead
  - name: delete a bridge using rhel-system-role network
    vars:
      network_connections:
        - name: "{{ bridge_nmcli_name }}"
          persistent_state: absent
    include_role:
      name: rhel-system-roles.network

