= playbook for setting up a new VM.


.guests attached to bridges
[%header,format=csv]
|===
name,         interface, MAC,               IP,              domain
*home*,    *public0*,    52:54:00:01:00:01, 192.168.1.1,     home
gateway,      enp1s0,    52:54:00:00:00:03, 192.168.1.3,     home

*net-test0*,  *test0*,   52:54:00:03:00:01, 192.168.134.1,   lab.example.com
 ,           ,           52:54:00:03:00:02, 192.168.134.2,   lab.example.com
gateway,      enp2s0,    52:54:00:03:00:03, 192.168.134.3,   lab.example.com
dhcp,         enp1s0,    52:54:00:03:00:04, 192.168.134.4,   lab.example.com
dns,          enp1s0,    52:54:00:03:00:05, 192.168.134.5,   lab.example.com
time,         enp1s0,    52:54:00:03:00:06, 192.168.134.6,   lab.example.com
git,          enp1s0,    52:54:00:03:00:07, 192.168.134.7,   lab.example.com
log,          enp1s0,    52:54:00:03:00:08, 192.168.134.8,   lab.example.com
metric,       enp1s0,    52:54:00:03:00:09, 192.168.134.9,   lab.example.com
id,           enp1s0,    52:54:00:03:00:10, 192.168.134.10,  lab.example.com
smtp,         enp1s0,    52:54:00:03:00:11, 192.168.134.11,  lab.example.com
repo-rhel8,   enp1s0,    52:54:00:03:00:12, 192.168.134.12,  lab.example.com
repo-rhel9,   enp1s0,    52:54:00:03:00:13, 192.168.134.13,  lab.example.com

controller,   enp1s0,    52:54:00:03:00:20, 192.168.134.20,  lab.example.com
hub,          enp1s0,    52:54:00:03:00:21, 192.168.134.21,  lab.example.com
ee,           enp1s0,    52:54:00:03:00:22, 192.168.134.22,  lab.example.com
database,     enp1s0,    52:54:00:00:00:23, 192.168.134.23,  lab.example.com

previous attempts,,,,

name1,         enp1s0,   52:54:00:00:00:12, 192.168.1.12, lab.example.com
git1,            eth0,   52:54:00:00:00:13, 192.168.1.13, lab.example.com
repo1,           eth0,   52:54:00:00:00:14, 192.168.1.14, lab.example.com
builder1,      enp1s0,   52:54:00:00:00:15, 192.168.1.15, lab.example.com
controller1,     eth0,   52:54:00:00:00:16, 192.168.1.16, lab.example.com
antora1,         eth0,   52:54:00:00:00:17, 192.168.1.17, lab.example.com
jenkins1,        eth0,   52:54:00:00:00:18, 192.168.1.18, lab.example.com
capsule1,        eth0,   52:54:00:00:00:19, 192.168.1.19, lab.example.com
builder2,      enp1s0,   52:54:00:00:00:20, 192.168.1.20,  lab.example.com
control2,      enp1s0,   52:54:00:00:00:21, 192.168.1.21,  lab.example.com
hub2,          enp1s0,   52:54:00:00:00:22, 192.168.1.22,  lab.example.com
*private0*,   *privbr0*, 52:54:00:01:00:01, 192.168.152.1,  private.example.com
guest1,       enp2s0,    52:54:00:01:00:02, 192.168.152.2,  private.example.com
guest2,       eth0,      52:54:00:01:00:03, 192.168.152.3,  private.example.com
guest4,          eth0,   52:54:00:01:00:04, 192.168.152.4, private.example.com
capsule1,        eth0,   52:54:00:01:00:05, 192.168.152.4,  private.example.com
isolatedn1,      eth0,   52:54:00:01:00:06, 192.168.152.5,  private.example.com
*private1*,   *privbr1*, 52:54:00:02:00:01, 192.168.162.1,  private.example.com
guest2,       eth1,      52:54:00:02:00:02, 192.168.162.3,  private.example.com
guest3,       eth1,      52:54:00:02:00:03, 192.168.162.2,  private.example.com

|===

get the code

[source,shell]
....
REPOSITORY=vm-aap2-hybrid
git clone https://github.com/nickhardiman/$REPOSITORY
cd $REPOSITORY
....

Install collections and roles to ~/.ansible/. 
Some collections are Red Hat Certified, from Ansible Automation Hub.
This requires an offline token. 

[source,shell]
....
export ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN=eyJhbGciOi...
ansible-galaxy collection install -r collections/requirements.yml 
ansible-galaxy role install -r roles/requirements.yml 
....

== AAP1

Create

build the machines

[source,shell]
....
ansible-playbook \
  --ask-become-pass  \
  -e 'rhsm_user=RH_user'  \
  -e 'rhsm_password=RH_password' \
  -e 'rhsm_pool_id=12345'  \
  main.yml
....

Destroy

This has the power to remove any local libvirt virtual machine, so it's dangerous. 

[source,shell]
....
ansible-playbook  --ask-become-pass  delete.yml
....

or something similar like

[source,shell]
....
ansible-playbook \
  --inventory=./inventory-hypervisor.ini  \
  --become-password-file=~/my-pass \
  --extra-var='hosts=["kvm-guest"]' \
  delete.yml 
....

== AAP2

Create

required?
  --playbook-artifact-enable=false \

[source,shell]
....
ansible-navigator run main.yml \
  --become-password-file=~/my-pass \
  --mode=stdout \
  --eei hub1.lab.example.com/my_new_ee  \
  --extra-var='rhsm_user=RH_user'  \
  --extra-var='rhsm_password=RH_password' \
  --extra-var='rhsm_pool_id=12345'  
....

