---
# virt-install
# These values override defaults.
# default variables and their values are listed here. 
#   https://github.com/nickhardiman/libvirt-guest/blob/main/defaults/main.yml

# compute 
# default 2 cores
# default 4GiB memory

# storage
# default 30GB disk

# network
nics:
- 
  name: enp1s0
  mac: "{{ public_mac_prefix }}:00:03"
  net: "{{ public_libvirt_name }}"
  # IP from the public network's DHCP service
  ip: 192.168.1.3
- 
  name: enp2s0
  mac: "{{ lab_mac_prefix }}:00:03"
  net: "{{ lab_libvirt_name }}"
  # IP is static
  ip: "{{ lab_net_prefix }}.3"

net_services:
- dns
- http
- https
- ssh

# OS
host: gateway
fqdn: "{{ host }}.lab.example.com"
RPMs: 
- httpd
- squid
- bind

# kickstart
kickstart_template: "{{ fqdn }}.ks.j2"

# accounts
