---
# virt-install
# These values override defaults.
# default variables and their values are listed here. 
#   https://github.com/nickhardiman/libvirt-guest/blob/main/defaults/main.yml

# compute 
# default 4 cores

# storage
# default 30GB disk

# network
# MAC addresses are listed here.
#   https://hardiman.consulting/rhel/9/unsorted/host1-libvirt-network.html
nics:
- 
  name: enp1s0
  mac: "52:54:00:00:00:03"
  net: public0
  # !!! get rid of this?
  # IP from DHCP
  ip: 192.168.1.3
- 
  name: enp2s0
  mac: "{{ mac_prefix }}:00:03"
  net: net-lab
  # !!! get rid of this?
  # IP from DHCP
  ip: "{{ net_prefix }}.3"

net_services:
- dns
- http
- https
- ssh


# OS
host: gateway
fqdn: "{{ host }}.lab.example.com"
RPMs: 
- httpd
- squid
- bind

# kickstart

# accounts

