---

# Ansible automation hub requires authentication.
# Use your offline token here (not the much larger access token that expires in 5 minutes)
# This token is revoked. 
# create a token at https://console.redhat.com/ansible/automation-hub/token#
# revoke a token at https://sso.redhat.com/auth/realms/redhat-external/account/applications
my_offline_token: xxxxx


# accounts
user_ansible_password: Password;1
# server certificate
server_dir: /root/ca
server_secret_passphrase: redhat
ca_secret_passphrase: redhat


# network
#
# !!! duplicates. defined here and in host_vars
# to list keys of this dict of dicts in a loop, use: 
#       loop: "{{ address | list }}"
address:
  gateway:
    mac: "{{ lab_mac_prefix }}:00:03"
    ip_last_octet: "3"
    ipv4: "{{ lab_net_prefix + '.3' }}"
  ipsal:
    mac: "{{ lab_mac_prefix }}:00:04"
    ip_last_octet: "4"
    ipv4: "{{ lab_net_prefix + '.4' }}"
  id:
    mac: "{{ lab_mac_prefix }}:00:05"
    ip_last_octet: "5"
    ipv4: "{{ lab_net_prefix  + '.5' }}"
  message:
    mac: "{{ lab_mac_prefix }}:00:06"
    ip_last_octet: "6"
    ipv4: "{{ lab_net_prefix  + '.6' }}"
  monitor:
    mac: "{{ lab_mac_prefix }}:00:07"
    ip_last_octet: "7"
    ipv4: "{{ lab_net_prefix  + '.7' }}"
  git:
    mac: "{{ lab_mac_prefix }}:00:08"
    ip_last_octet: "8"
    ipv4: "{{ lab_net_prefix  + '.8' }}"


