---

# Ansible automation hub requires authentication.
# Use your offline token here (not the much larger access token that expires in 5 minutes)
# This token is revoked. 
# create a token at https://console.redhat.com/ansible/automation-hub/token#
# revoke a token at https://sso.redhat.com/auth/realms/redhat-external/account/applications
my_offline_token: xxxxx


# accounts
user_ansible_password: Password;1
# server certificate
server_dir: /root/ca
server_secret_passphrase: redhat
ca_secret_passphrase: redhat


# network
# MAC addresses are listed here.
#   https://hardiman.consulting/rhel/9/unsorted/host1-libvirt-network.html
public_net_short_name: public
public_libvirt_name:   "net{{ public_net_short_name }}0"
public_mac_prefix: "52:54:00:00"
lab_net_short_name: lab
lab_libvirt_name:   "net{{ lab_net_short_name }}0"
lab_net_prefix: "192.168.135"
lab_mac_prefix: "52:54:00:02"

