---

# Ansible automation hub requires authentication.
# Use your offline token here (not the much larger access token that expires in 5 minutes)
# This token is revoked. 
# create a token at https://console.redhat.com/ansible/automation-hub/token#
# revoke a token at https://sso.redhat.com/auth/realms/redhat-external/account/applications
my_offline_token: xxxxx


# accounts
user_ansible_password: Password;1
# server certificate
server_dir: /root/ca
server_secret_passphrase: redhat
ca_secret_passphrase: redhat

# network 
net_short_name: lab
net_octet: "134"
net_prefix: "192.168.{{ net_octet }}"
libvirt_net_name: "net-{{ net_short_name }}"
mac_prefix: "52:54:00:03"
bridge_mac: "{{ mac_prefix }}:00:01"
bridge_ip_cidr: "{{ net_prefix }}.1/24"
bridge_nmcli_name: "bridge-{{ net_short_name }}"
bridge_device_name: "br{{ net_short_name }}"


