---
# virt-install
# These values override defaults.
# default variables and their values are listed here. 
#   https://github.com/nickhardiman/libvirt-guest/blob/main/defaults/main.yml

# compute 
# default 2 cores
# default 4GiB memory

# storage
# default 30GB disk

# network
# MAC addresses are listed here.
#   https://hardiman.consulting/rhel/9/unsorted/host1-libvirt-network.html
nics:
- 
  name: enp1s0
  mac: "{{ lab_mac_prefix }}:00:06"
  net: "{{ lab_libvirt_name }}"
  # !!! get rid of this?
  # used in 
  # ansible_collections/nick/platform/roles/hosts_record/tasks/main.yml
  # IP from DHCP
  ip: "{{ lab_net_prefix }}.6"

net_services:
- http
- https
- ssh

# OS
host: message
fqdn: "{{ host }}.lab.example.com"
RPMs: 
- postfix

# kickstart
kickstart_template: "kvm-guest.ks.j2"

# accounts

