---
# virt-install
# These values override defaults.
# default variables and their values are listed here. 
#   https://github.com/nickhardiman/libvirt-guest/blob/main/defaults/main.yml
# No gitlab packages for RHEL 9.
# Gitlab packages for RHEL 8 are here.
#   https://packages.gitlab.com/app/gitlab/gitlab-ce/search?q=gitlab-ce&filter=all&dist=el%2F8
install_iso: /var/lib/libvirt/images/rhel-8.6-x86_64-dvd.iso
os_variant: rhel8.5
 

# compute 
# double the default
cpus: 4
ram: 8192

# storage
# default 30GB disk

# network
# MAC addresses are listed here.
#   https://hardiman.consulting/rhel/9/unsorted/host1-libvirt-network.html
nics:
- 
  name: enp1s0
  mac: "{{ lab_mac_prefix }}:00:08"
  net: net-lab
  # !!! get rid of this?
  # IP from DHCP
  ip: "{{ lab_net_prefix }}.8"

net_services:
- http
- https
- ssh


# OS
host: log
fqdn: "{{ host }}.lab.example.com"
RPMs: 
- httpd
- python3-libsemanage


# kickstart

# accounts

