---
# virt-install
# These values override defaults.
# default variables and their values are listed here. 
#   https://github.com/nickhardiman/libvirt-guest/blob/main/defaults/main.yml

# compute 
# default 2 cores
# default 4GiB memory

# storage
# smaller than the 
# default 30GB disk
# size in GiB
disk_size: 13
# Add up the sizes below and make sure they fit in the disk_size.
# partitions
# 1 for /boot/efi                600M
# 2 for /boot                    1024M
# 3 LVM Physical Volume          11G * 1024 = 11264M
pv_size: 11264
# LVM logical volume for /root    4G * 1024 = 4096M
lv_root: 4096
# LVM logical volume for /var     4G * 1024 = 4096M
lv_var: 4096
# LVM volume for swap: 256M

# network
# MAC addresses are listed here.
#   https://hardiman.consulting/rhel/9/unsorted/host1-libvirt-network.html
nics:
- 
  name: enp1s0
  mac: "{{ lab_mac_prefix }}:00:04"
  net: "{{ lab_libvirt_name }}"
  # IP is static. No DHCP in lab network yet.  
  # see kickstart. 
  ip: "{{ lab_net_prefix }}.4"

net_services:
  - ssh
  - http
  - https
  - dhcp

# OS
host: ipsal
fqdn: "{{ host }}.lab.example.com"
RPMs: 
- dhcp-server
- python3-cryptography

# kickstart
kickstart_template: "{{ fqdn }}.ks.j2"

# accounts
