---
# virt-install
# These values override defaults.
# default variables and their values are listed here. 
#   https://github.com/nickhardiman/libvirt-guest/blob/main/defaults/main.yml

# compute 
# default 2 cores
# default 4GiB memory

# storage
# default 30GB disk

# network
# MAC addresses are listed here.
#   https://hardiman.consulting/rhel/9/unsorted/host1-libvirt-network.html
nics:
- 
  name: enp1s0
  mac: "{{ lab_mac_prefix }}:00:05"
  net: "{{ lab_libvirt_name }}"
  # !!! get rid of this?
  # used in 
  # ansible_collections/nick/platform/roles/hosts_record/tasks/main.yml
  # interface IP provided by DHCP, prob. shouldnt be here too. 
  ip: "{{ lab_net_prefix }}.5"

net_services:
  - ssh
  - http
  - https
  - dhcp

# OS
host: id
fqdn: "{{ host }}.lab.example.com"
RPMs: 
- ipa-server 
- ipa-server-dns
# !!! how about this on the controller node? 
# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html-single/installing_identity_management/index#installing-the-ansible-freeipa-package_server-ansible
#   ansible-freeipa

# kickstart
kickstart_template: "kvm-guest.ks.j2"

# accounts

